[zsh.files]
"dots/zsh/zshrc" = "~/.zshrc"
"dots/zsh/zshenv" = "~/.zshenv"
"dots/zsh/custom_management.zsh" = "~/.oh-my-zsh/custom/custom_management.zsh"
"dots/zsh/utils.zsh" = "~/.oh-my-zsh/custom/utils.zsh"

[starship.files]
"dots/starship/starship.toml" = "~/.config/starship.toml"

[vim.files]
"dots/vim/vimrc" = "~/.vimrc"

[git.files]
"dots/git/gitconfig" = "~/.gitconfig"

[alacritty.files]
"dots/alacritty/config.toml" = "~/.config/alacritty/alacritty.toml"
"dots/alacritty/monokai_pro.toml" = "~/.config/alacritty/themes/monokai_pro.toml"

[gitui.files]
"dots/gitui/key_bindings.ron" = "~/.config/gitui/key_bindings.ron"
"dots/gitui/theme.ron" = "~/.config/gitui/theme.ron"

[helix.files]
"dots/helix/config.toml" = "~/.config/helix/config.toml"

[zellij.files]
"dots/zellij/config.kdl" = "~/.config/zellij/config.kdl"

[fish.files]
"dots/fish/config.fish" = "~/.config/fish/config.fish"
"dots/fish/completions" = { target = "~/.config/fish/completions", type = "symbolic" }
"dots/fish/functions" = "~/.config/fish/functions"

[codex.files]
"dots/codex/private-dotfiles/codex/config.toml" = "~/.codex/config.toml"
"dots/codex/auth.json" = "~/.codex/auth.json"
